# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
# Tagging
- docker tag udagram-api-feed philasande/udagram-api-feed:v1
- docker tag udagram-api-user philasande/udagram-api-user:v1
- docker tag udagram-frontend philasande/udagram-frontend:v1
- docker tag udagram-reverseproxy philasande/udagram-reverseproxy:v1
# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push philasande/udagram-api-feed:v1
- docker push philasande/udagram-api-user:v1
- docker push philasande/udagram-frontend:v1
- docker push philasande/udagram-reverseproxy:v1